"""
Script to inspect the actual database schema and generate documentation.

Generates DATABASE_SCHEMA.md with current schema structure for Cursor/AI reference.
Includes all user schemas (public, embedding, semantic_tree_v2, etc.) excluding
information_schema and PostgreSQL system schemas.

Run: python inspect_schema.py
"""
import os
import sys
from pathlib import Path
from datetime import datetime

# Add app directory to path
sys.path.insert(0, str(Path(__file__).parent))

from sqlalchemy import create_engine, text, inspect

# Override DATABASE_URL to use localhost:5433
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql+psycopg2://badger:badgerpass@localhost:5433/badgerdb")

SCHEMA_DOC_PATH = Path(__file__).parent / "DATABASE_SCHEMA.md"

# Schemas to exclude from documentation (PostgreSQL system schemas)
EXCLUDED_SCHEMAS = frozenset({
    "information_schema",
    "pg_catalog",
    "pg_toast",
    "pg_temp_1",
    "pg_toast_temp_1",
})


def _doc_table(doc_lines: list, inspector, schema: str, table: str, qualified_name: str) -> None:
    """Append table documentation (columns, FKs, indexes) to doc_lines."""
    doc_lines.append(f"### Table: `{qualified_name}`")
    doc_lines.append("")

    columns = inspector.get_columns(table, schema=schema)
    doc_lines.append("| Column | Type | Nullable | Default |")
    doc_lines.append("|--------|------|----------|---------|")
    for col in columns:
        col_type = str(col["type"])
        nullable = "YES" if col["nullable"] else "NO"
        default = str(col.get("default", "")) if col.get("default") else ""
        doc_lines.append(f"| `{col['name']}` | `{col_type}` | {nullable} | {default} |")
    doc_lines.append("")

    fks = inspector.get_foreign_keys(table, schema=schema)
    if fks:
        doc_lines.append("**Foreign Keys:**")
        doc_lines.append("")
        for fk in fks:
            cols = ", ".join(fk["constrained_columns"])
            ref_table = fk["referred_table"]
            ref_schema = fk.get("referred_schema") or "public"
            ref_cols = ", ".join(fk["referred_columns"])
            if ref_schema == "public":
                doc_lines.append(f"- `{cols}` → `{ref_table}({ref_cols})`")
            else:
                doc_lines.append(f"- `{cols}` → `{ref_schema}.{ref_table}({ref_cols})`")
        doc_lines.append("")

    indexes = inspector.get_indexes(table, schema=schema)
    if indexes:
        doc_lines.append("**Indexes:**")
        doc_lines.append("")
        for idx in indexes:
            idx_cols = ", ".join(idx["column_names"])
            unique = "UNIQUE " if idx.get("unique", False) else ""
            doc_lines.append(f"- `{idx['name']}`: {unique}`{idx_cols}`")
        doc_lines.append("")

    doc_lines.append("---")
    doc_lines.append("")


def generate_schema_doc():
    """Generate markdown documentation of the database schema."""
    print(f"Connecting to: {DATABASE_URL.replace('badgerpass', '***')}")
    print("=" * 80)

    doc_lines = []
    doc_lines.append("# Database Schema Documentation")
    doc_lines.append("")
    doc_lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    doc_lines.append("")
    doc_lines.append("This document is auto-generated by `inspect_schema.py`.")
    doc_lines.append("It provides a snapshot of the current database schema for reference.")
    doc_lines.append("")
    doc_lines.append("---")
    doc_lines.append("")

    try:
        engine = create_engine(DATABASE_URL)
        inspector = inspect(engine)

        all_schemas = inspector.get_schema_names()
        user_schemas = sorted(s for s in all_schemas if s not in EXCLUDED_SCHEMAS and not s.startswith("pg_"))

        doc_lines.append("## Schemas")
        doc_lines.append("")
        doc_lines.append(f"Documented schemas: `{', '.join(user_schemas)}`")
        doc_lines.append("")
        doc_lines.append("*(Excludes: information_schema, pg_catalog, pg_toast, and other system schemas)*")
        doc_lines.append("")
        doc_lines.append("---")
        doc_lines.append("")

        for schema in user_schemas:
            schema_title = schema.replace("_", " ").title()
            doc_lines.append(f"## {schema_title} Schema")
            doc_lines.append("")
            doc_lines.append(f"*Schema: `{schema}`*")
            doc_lines.append("")

            tables = inspector.get_table_names(schema=schema)
            if tables:
                for table in sorted(tables):
                    qualified = f"{schema}.{table}" if schema != "public" else table
                    _doc_table(doc_lines, inspector, schema, table, qualified)
            else:
                doc_lines.append(f"No tables found in `{schema}` schema.")
                doc_lines.append("")
                doc_lines.append("---")
                doc_lines.append("")

        # Custom types (for schemas that define them, e.g. semantic_tree_v2.vault_role)
        doc_lines.append("## Custom Types")
        doc_lines.append("")
        with engine.connect() as conn:
            result = conn.execute(text("""
                SELECT n.nspname AS schema_name, t.typname AS type_name, t.typtype
                FROM pg_type t
                JOIN pg_namespace n ON n.oid = t.typnamespace
                WHERE n.nspname = ANY(:schemas)
                  AND t.typtype = 'e'
                  AND t.typname NOT LIKE 'pg_%'
                ORDER BY n.nspname, t.typname
            """), {"schemas": list(user_schemas)})
            enum_types = result.fetchall()
        if enum_types:
            doc_lines.append("| Schema | Type | Kind |")
            doc_lines.append("|--------|------|------|")
            for row in enum_types:
                doc_lines.append(f"| `{row[0]}` | `{row[1]}` | enum |")
            doc_lines.append("")
        else:
            doc_lines.append("No custom enum types found.")
            doc_lines.append("")
        doc_lines.append("---")
        doc_lines.append("")

        # Functions (exclude public to avoid extension noise: pgcrypto, vector, etc.)
        doc_lines.append("## Functions")
        doc_lines.append("")
        doc_lines.append("*(Excludes public schema to avoid extension functions from pgcrypto, vector, etc.)*")
        doc_lines.append("")
        non_public_schemas = [s for s in user_schemas if s != "public"]
        with engine.connect() as conn:
            result = conn.execute(text("""
                SELECT n.nspname AS schema_name, p.proname AS func_name,
                       pg_get_function_arguments(p.oid) AS args,
                       pg_get_function_result(p.oid) AS returns
                FROM pg_proc p
                JOIN pg_namespace n ON n.oid = p.pronamespace
                WHERE n.nspname = ANY(:schemas)
                  AND p.prokind = 'f'
                ORDER BY n.nspname, p.proname
            """), {"schemas": non_public_schemas})
            functions = result.fetchall()
        if functions:
            doc_lines.append("| Schema | Function | Arguments | Returns |")
            doc_lines.append("|--------|----------|-----------|---------|")
            for row in functions:
                args = (row[2] or "")[:80]
                returns = (row[3] or "")[:40]
                doc_lines.append(f"| `{row[0]}` | `{row[1]}` | `{args}` | `{returns}` |")
            doc_lines.append("")
        else:
            doc_lines.append("No custom functions found.")
            doc_lines.append("")
        doc_lines.append("---")
        doc_lines.append("")

        # Statistics: row counts for all tables
        doc_lines.append("## Statistics")
        doc_lines.append("")
        doc_lines.append("### Row Counts")
        doc_lines.append("")
        with engine.connect() as conn:
            for schema in user_schemas:
                tables = inspector.get_table_names(schema=schema)
                for table in sorted(tables):
                    qualified = f"{schema}.{table}"
                    try:
                        result = conn.execute(
                            text(f'SELECT COUNT(*) FROM "{schema}"."{table}"')
                        )
                        count = result.scalar()
                        doc_lines.append(f"- `{qualified}`: **{count:,}** rows")
                    except Exception as e:
                        doc_lines.append(f"- `{qualified}`: Error counting - {e}")

        doc_lines.append("")
        doc_lines.append("---")
        doc_lines.append("")

        # Embedding model metadata (if embedding schema exists)
        if "embedding" in user_schemas:
            doc_lines.append("### Registered Embedding Models")
            doc_lines.append("")
            with engine.connect() as conn:
                try:
                    result = conn.execute(text("""
                        SELECT model_name, version, dimensions, table_location, loaded_at
                        FROM embedding.embedding_model
                        ORDER BY loaded_at DESC
                    """))
                    models = result.fetchall()
                    if models:
                        doc_lines.append("| Model | Version | Dimensions | Table Location | Loaded At |")
                        doc_lines.append("|-------|---------|------------|----------------|-----------|")
                        for model in models:
                            doc_lines.append(f"| `{model[0]}` | `{model[1]}` | {model[2]} | `{model[3]}` | {model[4]} |")
                    else:
                        doc_lines.append("No embedding models registered.")
                except Exception as e:
                    doc_lines.append(f"Error querying embedding_model: {e}")
            doc_lines.append("")
            doc_lines.append("---")
            doc_lines.append("")

        doc_lines.append("## Notes")
        doc_lines.append("")
        doc_lines.append("- This schema is automatically generated and should be updated when database structure changes")
        doc_lines.append("- Run `python inspect_schema.py` manually to regenerate this document")
        doc_lines.append("- The schema is automatically updated when `init_db()` is called")
        doc_lines.append("")

        SCHEMA_DOC_PATH.write_text("\n".join(doc_lines), encoding="utf-8")

        print("\n" + "=" * 80)
        print(f"Schema documentation generated: {SCHEMA_DOC_PATH}")
        print("=" * 80)

        return True

    except Exception as e:
        error_msg = f"\nError inspecting schema: {e}\n"
        print(error_msg)
        import traceback
        traceback.print_exc()

        error_doc = [
            "# Database Schema Documentation",
            "",
            f"**Last Update Attempt:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "## Error",
            "",
            f"Failed to generate schema documentation:",
            "",
            f"```",
            f"{str(e)}",
            f"```",
            "",
            "Please check database connection and try again.",
            "",
        ]
        SCHEMA_DOC_PATH.write_text("\n".join(error_doc), encoding="utf-8")

        return False


if __name__ == "__main__":
    success = generate_schema_doc()
    sys.exit(0 if success else 1)
